export const sidebarContent = {
  logo: "LSOgo",
  title: "Menu",
  dashboard: "Dashboard",
  calendar: "Kalendarz",
  schedule: "Harmonogram",
  ranking: "Ranking",
  history: "Historia",
  profile: "Profil",
  footer: "LSOGO",
  version: "v1.0",
  notifications: "Powiadomienia",
  messages: "Wiadomości",

  moderator: {
    dashboard: "Dashboard",
    users: "Użytkownicy",
    ranking: "Ranking",
    attendance: "Obecności",
    schedule: "Harmonogram",
    services: "Nabożeństwa",
    calendar: "Kalendarz",
    messages: "Wiadomości",
    notifications: "Powiadomienia",
    reports: "Raporty",
    profile: "Profil",
  },
};
